# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5106c86fa7168abb40d6304d4e8c4c548cde0717481c8433e662503470f8b800d8d6c6a6626e2d594e78c0f03252906a89c4ae631700e863e08258bdf9db8f7

test:
  secret_key_base: ed1b9c91293c6ae42c10cea3a9f8700e106fbbde7300f59cedc52c566fb9a58a485ab7cab567527383619b31fc9d3acca40cf204843bbff814bf7efdfa5093a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
